# Generated by Django 4.0.1 on 2022-01-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_employees_in_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fatherland',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
