# Generated by Django 4.0.1 on 2022-01-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('employees', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='body.employee')),
                ('name_address', models.CharField(max_length=100)),
                ('mail_index', models.PositiveIntegerField()),
            ],
        ),
    ]
