# Generated by Django 4.0.1 on 2022-01-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body', '0002_employees_in_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='body.employee')),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
